name: CI

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - main
    - master

jobs:
  conda-pyhist:
    name: Conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python_version: [2.7, 3.5, 3.6]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: PyHIST
          environment-file: conda/environment.yml
          auto-activate-base: false
      - run: .github/workflows/ci.sh